### ISSUE TITLE
Create a plan for backend

### ISSUE THREAD

**Issue by Hankier** [hqrEdu/ZeroToJuniorMapAlpha#2]
Prepare a plan for backend.

Include what technologies will be used. 

DoD:
Initial plan is created.
Task are described.

**Comment by iwannabedev** [comment]
Here's a first draft of tasks. Feel free to suggest any changes. Task 3 is optional for now and will be implemented later when/if time allows.

BE#1 Database
  - plan structure of DB
  - handle DB connection

BE#2 Flask
  - I HAVE NO 'F' IDEA ;p

BE#3 Authentication
  - implement Discord OAuth2
  - retrive user guild(s) and only allow "Zero To Junior" members
  - retrive user role(s) within our guild
